#!/usr/bin/env python3
"""Generate docs/QA_THRESHOLDS_TABLES.md from the shipped QA configs.

The per-detector limits live in the lookup tables of qa_config_cal.yaml and
qa_config_science.yaml (generated by gen_configs.py) and in
baselines/qa_thresholds_derived.json. This script renders them as markdown
tables so the threshold appendix of docs/QA_CHECKS_CATALOGUE.md always matches
what the engine actually applies. Re-run after regenerating the configs.
"""
import argparse
import json
from pathlib import Path

import yaml

from llamas_checks.paths import BASELINES_DIR, CONFIG_DIR

CAL_TYPES = [
    ("BIAS", "CAL.R-BIA", True),
    ("DARK", "CAL.R-DRK", True),
    ("LDLS_FLAT", "CAL.R-FLT", False),
    ("SKY_FLAT", "CAL.R-SKY", False),
    ("ARC_THAR", "CAL.R-ARC", False),
]
DEFAULT_OUT = Path(__file__).resolve().parents[1] / "docs" / "QA_THRESHOLDS_TABLES.md"


def fmt(value):
    if value is None:
        return "—"
    if isinstance(value, float):
        text = f"{value:.4f}".rstrip("0").rstrip(".")
        return text if text not in ("", "-0") else "0"
    return str(value)


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(fmt(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def modes_in(lookup):
    modes = []
    for per_det in lookup.values():
        for mode in per_det:
            if mode not in modes:
                modes.append(mode)
    return modes


def cal_type_section(name, prodcatg, has_level, detectors, tables, derived):
    out = [f"## {name} (`{prodcatg}`)", ""]
    edge, struct, sat = tables[f"edge_bg_{name}"], tables[f"struct_{name}"], tables[f"sat_{name}"]
    level = tables.get(f"level_{name}") if has_level else None
    n_files = {}
    for mode, per_det in derived["per_detector"][prodcatg].items():
        for det, entry in per_det.items():
            n_files[(det, mode)] = entry.get("n_files")
    for mode in modes_in(edge):
        header = ["detector", "n baseline", "edge-bg min", "edge-bg max"]
        if level:
            header += ["level min", "level max", "rms (robust) max"]
        header += ["row max", "col max"]
        if has_level:
            header += ["row FAIL max (4x)", "col FAIL max (4x)"]
        header += ["sat frac max"]
        rows = []
        for det in detectors:
            e = edge.get(det, {}).get(mode)
            s = struct.get(det, {}).get(mode)
            f = sat.get(det, {}).get(mode)
            row = [det, n_files.get((det, mode)),
                   e and e["min"], e and e["max"]]
            if level:
                lv = level.get(det, {}).get(mode)
                row += [lv and lv["med_min"], lv and lv["med_max"], lv and lv["rms_max"]]
            row += [s and s["row_max"], s and s["col_max"]]
            if has_level:
                row += [s and s.get("row_fail_max"), s and s.get("col_fail_max")]
            row += [f and f["frac_max"]]
            rows.append(row)
        out += [f"### {name} — readout mode {mode}", "", table(header, rows), ""]
    return out


def temperature_section(detectors, temp_table, derived):
    per_det = derived["ccd_temp"]["per_detector"]
    header = ["detector", "baseline median °C", "n baseline", "robust σ °C",
              "cold min", "warn above (WARN)", "fail above (FAIL)"]
    rows = []
    for det in detectors:
        t = temp_table.get(det, {})
        d = per_det.get(det, {})
        obs = d.get("observed", {})
        rows.append([det, d.get("baseline_med"), obs.get("n"), obs.get("sigma_robust"),
                     t.get("cold_min"), t.get("warn_max"), t.get("fail_max")])
    ct = derived["ccd_temp"]
    margins = ", ".join(f"{colour} WARN +{fmt(ct['warn_margin'][colour])} / FAIL +{fmt(ct['fail_margin'][colour])} °C"
                        for colour in ("red", "green", "blue"))
    return [
        "## CCD temperature (all rule sets, keyed on detector only)", "",
        f"Margins over each camera's own baseline median: {margins}. "
        f"Absolute shut-off FAIL above {fmt(ct['abs_fail_above'])} °C on every camera.", "",
        table(header, rows), "",
    ]


def shutter_section(derived):
    header = ["frame type", "abs tolerance (s)", "rel tolerance", "largest \\|SEXPTIME − REXPTIME\\| seen in baselines (s)"]
    rows = [[k, v["abs_tol"], v["rel_tol"], v.get("abs_delta_max")] for k, v in sorted(derived["shutter"].items())]
    return ["## Shutter consistency (`shutter_exptime_consistency`, FAIL)", "",
            "Passes when \\|SEXPTIME − REXPTIME\\| is within EITHER the absolute or the relative tolerance.", "",
            table(header, rows), ""]


def science_section(sci):
    rules = sci["rule_sets"]["SCIENCE"]["rules"]
    header = ["rule", "severity", "region / source", "limit"]
    rows = []
    for r in rules:
        if "header_check" in r:
            src = r["header_check"].get("source") or ", ".join(r["header_check"].get("per_extension_key", []))
            lim = r["header_check"].get("limits") or r.get("expected_from_lookup", {}).get("table")
            if isinstance(lim, dict):
                lim = ", ".join(f"{k} {fmt(v)}" for k, v in lim.items())
            elif lim:
                lim = f"lookup `{lim}` (per detector)"
            else:
                lim = f"abs {fmt(r['header_check'].get('abs_tol'))} s or rel {fmt(r['header_check'].get('rel_tol'))}"
        else:
            src = f"{r['region']} / {r['metric']}"
            lim = ", ".join(f"{k} {fmt(v)}" for k, v in r["limits"].items())
            if "min_exptime" in r:
                lim += f" (skip if exptime < {fmt(r['min_exptime'])} s)"
        rows.append([r["name"], r["severity"], src, lim])
    return ["## SCIENCE (`SCI.R-*`) static limits", "", table(header, rows), ""]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    cal = yaml.safe_load((CONFIG_DIR / "qa_config_cal.yaml").read_text())
    sci = yaml.safe_load((CONFIG_DIR / "qa_config_science.yaml").read_text())
    derived = json.loads((BASELINES_DIR / "qa_thresholds_derived.json").read_text())
    detectors = [e["name"] for e in cal["extensions"]]
    tables = cal["lookup_tables"]
    meta = derived["meta"]

    doc = [
        "# LLAMAS QA thresholds — per-detector tables",
        "",
        "> Generated by `scripts/gen_thresholds_doc.py` from `llamas_checks/configs/qa_config_cal.yaml`,",
        "> `qa_config_science.yaml` and `llamas_checks/baselines/qa_thresholds_derived.json`. Do not edit by hand;",
        "> re-run the script after `gen_configs.py`.",
        "",
        f"Baseline epochs: {', '.join(meta['epochs'])}; {meta['n_normal_records']} normal detector-frame records; "
        f"held out: {meta['excluded_odd']}. Method: {meta['robustness']}. Regions: {meta['region_convention']}.",
        "",
        "Units: ADU for levels, RMS and structure metrics; fraction of pixels for saturation; °C for temperature; "
        "seconds for shutter tolerances. Level and edge-background limits are a min–max band (WARN outside); "
        "RMS (1.4826 x MAD), structure (std of the per-row / per-column medians) and saturation are one-sided "
        "caps. On BIAS/DARK the row/col caps are WARN and the 4x \"FAIL max\" columns are the `*_gross` FAIL "
        "tier; on LDLS/ARC the structure cap is FAIL, on SKY it is WARN. Static FAIL rules on every set: "
        "`edge_saturated` (bottom-stripe median > 63000 ADU) and, on BIAS/DARK, `saturation_gross` "
        "(> 1 % of pixels above 63000 ADU). \"—\" means that readout mode is not modelled for "
        "that detector (the rule is SKIPPED, never failed). A missing camera in a frame is a placeholder "
        "extension and is skipped.",
        "",
    ]
    doc += shutter_section(derived)
    doc += temperature_section(detectors, tables["temp"], derived)
    doc += science_section(sci)
    for name, prodcatg, has_level in CAL_TYPES:
        doc += cal_type_section(name, prodcatg, has_level, detectors, tables, derived)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(doc).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
